apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 25
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        # image: nginx:stable
        image: nginxdemos/hello
        ports:
        - containerPort: 80


  
